Areas/AdminPanel/Models/Product/AddProductDTORequest.cs
namespace Vektorel_234_CRMWebUI.Areas.AdminPanel.Models.Product
{
    public class AddProductDTORequest
    {
        public string Name { get; set; }

        public string Description { get; set; }

        public Guid CategoryGUID { get; set; }

        public string ProductImage { get; set; }
    }
}

Areas/AdminPanel/Models/Product/ProductDTO.cs
namespace Vektorel_234_CRMWebUI.Areas.AdminPanel.Models.Product
{
    public class ProductDTO
    {
        public Guid GUID { get; set; }
        public string Ad { get; set; }
        public string KategoriAdi { get; set; }
        public Guid? KategoriGUID { get; set; }
        public string Aciklama { get; set; }
        public string OneCikanGorsel { get; set; }
    }
}

Areas/AdminPanel/Models/Product/UpdateProductDTORequest.cs
using System.Text.Json.Serialization;

namespace Vektorel_234_CRMWebUI.Areas.AdminPanel.Models.Product
{
    public class UpdateProductDTORequest
    {
        public Guid ProductGUID { get; set; }
        public string Name { get; set; }

        public string Description { get; set; }

        public Guid CategoryGUID { get; set; }

        [JsonIgnore(Condition =JsonIgnoreCondition.WhenWritingNull)]
        public string? ProductImage { get; set; }
    }
}

Areas/AdminPanel/Components/Category/CategoryDropDownViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RestSharp;
using System.Text.Json;
using Vektorel_234_CRM.Helper.Const;
using Vektorel_234_CRM.Helper.Result;
using Vektorel_234_CRM.Helper.SessionHelper;
using Vektorel_234_CRMWebUI.Areas.AdminPanel.Models.Category;
using Vektorel_234_CRMWebUI.Areas.AdminPanel.Models.Group;

namespace Vektorel_234_CRMWebUI.Areas.AdminPanel.Components.Category
{
    public class CategoryDropDownViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(Guid? productCategoryGuid, string ddlID)
        {
            var url = ApiEndpoint.ApiEndpointURL + "/Categories";
            var client = new RestClient(url);
            var request = new RestRequest(url, Method.Get);
            request.AddHeader("Content-Type", "application/json");
            request.AddHeader("Authorization", "Bearer " + SessionManager.loginResponseDTO.Token);

            RestResponse response = await client.ExecuteAsync(request);

            var responseObject = JsonSerializer.Deserialize<ApiResult<List<CategoryDTO>>>(response.Content);

            var categoryList = responseObject.Data;

            CategoryDropDownViewModel categoryDropDownViewModel = new CategoryDropDownViewModel();

            categoryDropDownViewModel.CategoryList = categoryList;
            categoryDropDownViewModel.ProductCategoryGUID = productCategoryGuid == Guid.Empty ? null : productCategoryGuid;
            categoryDropDownViewModel.ddlCateogryElementID = ddlID;

            return View("~/Areas/AdminPanel/Views/Shared/Component/Category/CategoryDropDown.cshtml", categoryDropDownViewModel);
        }
    }
}

Areas/AdminPanel/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using RestSharp;
using System.Net;
using System.Text.Json;
using Vektorel_234_CRM.Helper.Const;
using Vektorel_234_CRM.Helper.Result;
using Vektorel_234_CRM.Helper.SessionHelper;
using Vektorel_234_CRMWebUI.Areas.AdminPanel.Models.Product;
using Vektorel_234_CRMWebUI.Areas.AdminPanel.Models.User;

namespace Vektorel_234_CRMWebUI.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class ProductController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet("/Admin/Urunler")]
        public async Task<IActionResult> Index()
        {
            var url = ApiEndpoint.ApiEndpointURL + "/Products";
            var client = new RestClient(url);
            var request = new RestRequest(url, Method.Get);
            request.AddHeader("Content-Type", "application/json");
            request.AddHeader("Authorization", "Bearer " + SessionManager.loginResponseDTO.Token);

            RestResponse response = await client.ExecuteAsync(request);

            var responseObject = JsonSerializer.Deserialize<ApiResult<List<ProductDTO>>>(response.Content);

            var productList = responseObject.Data;

            //throw new Exception();
            // Test amaçlı yazıldııı
            return View(productList);

        }

        [HttpPost("/Admin/UrunEkle")]
        public async Task<IActionResult> Add(AddProductDTORequest productDTO, IFormFile productImage)
        {
            if (productImage is not null)
            {
                string fileName = productImage.FileName.Split('.')[productImage.FileName.Split('.').Length - 2] +"_"+Guid.NewGuid()+"."+productImage.FileName.Split('.')[productImage.FileName.Split('.').Length-1];

                string uploadFolder = Path.Combine(_webHostEnvironment.WebRootPath, "MediaUpload", fileName);

                using (var filestream  = new FileStream(uploadFolder,FileMode.Create))
                {
                    productImage.CopyTo(filestream);
                }
                productDTO.ProductImage = fileName;
            }
            
            


            var url = ApiEndpoint.ApiEndpointURL + "/Product";
            var client = new RestClient(url);
            var request = new RestRequest(url, Method.Post);
            request.AddHeader("Content-Type", "application/json");
            request.AddHeader("Authorization", "Bearer " + SessionManager.loginResponseDTO.Token);
            request.AddBody(productDTO);

            RestResponse response = await client.ExecuteAsync(request);

            var responseObject = JsonSerializer.Deserialize<ApiResult<bool>>(response.Content);

            var result = responseObject.Data;

            if (response.StatusCode==HttpStatusCode.OK)
            {
                return Json(new {success=true});
            }

            return Json(new { success = false });

        }
        
        [HttpPost("/Admin/UrunGuncelle")]
        public async Task<IActionResult> Update(UpdateProductDTORequest productDTO, IFormFile productImage)
        {
            if (productImage is not null)
            {
                
                string fileName = productImage.FileName.Split('.')[productImage.FileName.Split('.').Length - 2] +"_"+Guid.NewGuid()+"."+productImage.FileName.Split('.')[productImage.FileName.Split('.').Length-1];

                string uploadFolder = Path.Combine(_webHostEnvironment.WebRootPath, "MediaUpload", fileName);

                using (var filestream  = new FileStream(uploadFolder,FileMode.Create))
                {
                    productImage.CopyTo(filestream);
                }
                productDTO.ProductImage = fileName;
            }

            else
            {
                productDTO.ProductImage = null;
            }
            


            var url = ApiEndpoint.ApiEndpointURL + "/Product";
            var client = new RestClient(url);
            var request = new RestRequest(url, Method.Put);
            request.AddHeader("Content-Type", "application/json");
            request.AddHeader("Authorization", "Bearer " + SessionManager.loginResponseDTO.Token);
            request.AddBody(productDTO);

            RestResponse response = await client.ExecuteAsync(request);

            var responseObject = JsonSerializer.Deserialize<ApiResult<bool>>(response.Content);

            var result = responseObject.Data;

            if (response.StatusCode==HttpStatusCode.OK)
            {
                return Json(new {success=true});
            }

            return Json(new { success = false });

        }


        [HttpGet("/Admin/Urun/{productGUID}")]
        public async Task<IActionResult> GetProduct(Guid productGUID)
        {
            var url = ApiEndpoint.ApiEndpointURL + "/Product/" + productGUID;
            var client = new RestClient(url);
            var request = new RestRequest(url, Method.Get);
            request.AddHeader("Content-Type", "application/json");
            request.AddHeader("Authorization", "Bearer " + SessionManager.loginResponseDTO.Token);

            RestResponse response = await client.ExecuteAsync(request);

            var responseObject = JsonSerializer.Deserialize<ApiResult<ProductDTO>>(response.Content);

            var product = responseObject.Data;

            return Json(product);

        }
    }
}

Areas/AdminPanel/Views/Product/Index.cshtml
@using Vektorel_234_CRMWebUI.Areas.AdminPanel.Models.Product
@model List<ProductDTO>
@{
    ViewData["Title"] = "Ürünler";
    Layout = "~/Areas/AdminPanel/Views/Shared/_Layout.cshtml";
}
<style>

</style>
<div class="card">
    <div class="card-header">
        <div class="card-tools">
            <a href="#" class="btn btn-primary btn-block mb-1" data-toggle="modal" data-target="#modal-AddProduct">Yeni Ürün Ekle</a>
        </div>
    </div>
    <div class="card-body">

        <table id="tblUrunler" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Ürün Resim</th>
                    <th>Ad</th>
                    <th>Kategori</th>
                    <th>İşlemler</th>
                </tr>
            </thead>
            <tbody>

                @{
                    foreach (var item in Model)
                    {
                        string imagePath = "/MediaUpload/" + item.OneCikanGorsel;

                            <tr>
                                <td><img src="@imagePath" width="100" /></td>
                                <td>@item.Ad</td>
                                <td>@item.KategoriAdi</td>
                                <td><button type="button" class="btn btn-block btn-warning btn-sm btnGetProductDetail" data-toggle="modal" data-target="#modal-ProductDetail" data-guid=@item.GUID data-categoryGuid="@item.KategoriGUID">Görüntüle</button></td>
                            </tr>
                    }



                }
            </tbody>

        </table>
    </div>
</div>


<div class="modal fade" id="modal-AddProduct">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Yeni Ürün Ekle</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group row">
                    <label for="txtUrunAdi_Add" class="col-sm-2 col-form-label">Adı</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="txtUrunAdi_Add">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="txtUrunAciklama_Add" class="col-sm-2 col-form-label">Açıklama</label>
                    <div class="col-sm-10">
                        <textarea id="txtUrunAciklama_Add" rows="10" style="width:100%"></textarea>
                    </div>
                </div>



                <div class="form-group row">
                    <label for="ddlProductCategory_Add" class="col-sm-2 col-form-label">Kategori</label>
                    <div class="col-sm-10" id="divUserGroup_Add">
                        @await Component.InvokeAsync("CategoryDropDown", new { productCategoryGuid = Guid.Empty, ddlID = "ddlProductCategory_Add" })

                    </div>
                </div>

                <div class="form-group row">
                    <!-- <label for="customFile">Custom File</label> -->
                    <label for="fuProductImage" class="col-sm-4 col-form-label">Öne Çıkan Görsel</label>
                    <div class="custom-file col-sm-8">
                        <input type="file" class="custom-file-input" id="fuProductImage">
                        <label class="custom-file-label" for="customFile"></label>
                    </div>
                </div>

            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Kapat</button>
                <button type="button" class="btn btn-primary" id="btnAddProduct">Kaydet</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<div class="modal fade" id="modal-ProductDetail">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="HProductName">Ürün Güncelle</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group row">
                    <label for="txtUrunAdi_Update" class="col-sm-2 col-form-label">Adı</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="txtUrunAdi_Update">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="txtUrunAciklama_Update" class="col-sm-2 col-form-label">Açıklama</label>
                    <div class="col-sm-10">
                        <textarea id="txtUrunAciklama_Update" rows="10" style="width:100%"></textarea>
                    </div>
                </div>



                <div class="form-group row">
                    <label for="divProductCategory_Update" class="col-sm-2 col-form-label">Kategori</label>
                    <div class="col-sm-10" id="divProductCategory_Update">
                       

                    </div>
                </div>

                <div class="form-group row">
                    <!-- <label for="customFile">Custom File</label> -->
                    <label for="fuProductImage_Update" class="col-sm-4 col-form-label">Öne Çıkan Görsel</label>
                    <div class="customFile_Update col-sm-8">
                        <input type="file" class="custom-file-input" id="fuProductImage_Update">
                        <label class="custom-file-label" for="customFile_Update"></label>
                    </div>
                </div>

            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Kapat</button>
                <button type="button" class="btn btn-primary" id="btnUpdateProduct">Güncelle</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<script>
    $(function () {
        $("#tblUrunler").DataTable({
            "responsive": true, "lengthChange": false, "autoWidth": false,
            "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#tblUrunler_wrapper .col-md-6:eq(0)');

        $('#txtUrunAciklama_Add').summernote()

        $('#btnAddProduct').click(function () {


            var productDTO = {
                Name: $('#txtUrunAdi_Add').val(),
                Description: $('#txtUrunAciklama_Add').summernote('code'),
                CategoryGUID: $('#ddlProductCategory_Add').val()
            };

            var files = $('#fuProductImage').prop('files');

            var formData = new FormData();
            formData.append("Name", productDTO.Name);
            formData.append("Description", productDTO.Description);
            formData.append("CategoryGUID", productDTO.CategoryGUID);
            formData.append("productImage", files[0]);


            $.ajax({

                url: '/Admin/UrunEkle',
                type: 'post',
                data: formData,
                cahce: false,
                contentType: false,
                processData: false,
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("XSRF-Token", $('input:hidden[name="__RequestVerificationToken"]').val())
                },
                success: function (response) {
                    console.log(response);
                    if (response.success) {
                        Swal.fire({
                            title: "İşlem Başarılı!",
                            html: "Ürün Başarıyla Eklenmiştir. Sayfa Tekrar Yükleniyor.",
                            icon: "success",
                            timer: 3000,
                        }).then((result) => {
                            window.location.reload();
                        });

                    }

                    else {
                        Swal.fire({
                            title: "HATA OLUŞTU!",
                            text: response.hataAciklama,
                            icon: "error"
                        });
                    }
                }

            });
        });

        $('#btnUpdateProduct').click(function () {

            var productGUID = $(this).attr('data-guid');
            var productDTO = {
                Name: $('#txtUrunAdi_Update').val(),
                Description: $('#txtUrunAciklama_Update').summernote('code'),
                CategoryGUID: $('#ddlProductCategory_Update').val(),
                ProductGUID: productGUID
            };

            var files = $('#fuProductImage_Update').prop('files');

            var formData = new FormData();
            formData.append("Name", productDTO.Name);
            formData.append("Description", productDTO.Description);
            formData.append("CategoryGUID", productDTO.CategoryGUID); 
            formData.append("ProductGUID", productDTO.ProductGUID);

            if (files.length > 0) {
                formData.append("productImage", files[0]);

            }



            $.ajax({

                url: '/Admin/UrunGuncelle',
                type: 'post',
                data: formData,
                cahce: false,
                contentType: false,
                processData: false,
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("XSRF-Token", $('input:hidden[name="__RequestVerificationToken"]').val())
                },
                success: function (response) {
                    console.log(response);
                    if (response.success) {
                        Swal.fire({
                            title: "İşlem Başarılı!",
                            html: "Ürün Başarıyla Güncellenmiştir. Sayfa Tekrar Yükleniyor.",
                            icon: "success",
                            timer: 3000,
                        }).then((result) => {
                            window.location.reload();
                        });

                    }

                    else {
                        Swal.fire({
                            title: "HATA OLUŞTU!",
                            text: response.hataAciklama,
                            icon: "error"
                        });
                    }
                }

            });
        });

        $('.btnGetProductDetail').click(function () {
            var guid = $(this).attr('data-guid');
            var productCategoryGuid = $(this).attr('data-categoryGuid');
            var ddlID = "ddlProductCategory_Update"
            $.ajax({
                url: "/Admin/Urun/" + guid,
                type: "get",
                success: function (response) {
                    $('#HProductName').html('').append(response.Ad);
                    $('#txtUrunAdi_Update').val(response.Ad);
                    $('#txtUrunAciklama_Update').summernote('code', response.Aciklama);
                   


                    $.ajax({
                        url: "/Admin/InvokeCategoryDropDown",
                        type: "get",
                        data: { productCategoryGuid, ddlID },
                        success: function (result) {
                            $('#divProductCategory_Update').html('').append(result);
                        }

                    });

                    $('#btnUpdateProduct').attr('data-guid', guid)

                },
                Error: function (err) {
                    Swal.fire({
                        title: "HATA OLUŞTU!",
                        text: err,
                        icon: "error"
                    });
                }




            });



        });

        
    });

</script>